## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

artemis = ENC(1024:6EA35FE8759917B3360DA2888E632AA8D7D34418E07994C085AE4D7C7B8DA15A:AF98BCE7C0E087FF3C240B9CF791E4ED859047AEE2EE123EC0728EA8F5E5AF02A68822EAC40561B1721F9ECB9DBE1664B67D1A5B1499AB8A3BD32890CA3D2413)
admin=admin
